"""Initial migration

Revision ID: c7b2dcfffeca
Revises: 
Create Date: 2024-10-17 10:15:23.606309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b2dcfffeca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideas_id'), 'ideas', ['id'], unique=False)
    op.create_index(op.f('ix_ideas_title'), 'ideas', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ideas_title'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_id'), table_name='ideas')
    op.drop_table('ideas')
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
